services:
  thumbor:
    image: ghcr.io/imgproxy/imgproxy:latest
    restart: always
    networks:
      - thumbor

    ports:
      - 5000:8080

    environment:
      - IMGPROXY_KEY=${IMGPROXY_KEY}
      - IMGPROXY_SALT=${IMGPROXY_SALT}

networks:
  thumbor:
    driver: bridge
