
server {
  server_name imgproxy.pekkis.eu;

  root /var/www/html;

  proxy_cache_path /var/www/cache levels=1:2 keys_zone=my-cache:8m max_size=10000m inactive=600m;
  proxy_temp_path /var/www/cache/tmp;

  location / {
    proxy_pass http://localhost:5000;
    proxy_cache my-cache;
    proxy_cache_valid 200 302 60m;
    proxy_cache_valid 404 1m;
  }

  listen 80;
}

